import { test } from "node:test";
import assert from "node:assert/strict";
import { elementsIn, tableEdges, textEdges, judgeRules, scoringSentence } from "../lib/rules.mjs";

const judge = (edges) => judgeRules([{ name: "t", edges }]).verdict;

test("element names in three languages, Russian cases", () => {
	assert.deepEqual(
		elementsIn("Дерево питает Огонь, огня, Землю, металлом, Воды; wood Fire 土 金 水").map((x) => x.el),
		["wood", "fire", "fire", "earth", "metal", "water", "wood", "fire", "earth", "metal", "water"],
	);
	assert.deepEqual(elementsIn("водитель провода огород земляника"), []);
});

test("header table, Russian", () => {
	const rows = [
		["Стихия", "Порождает", "Преодолевает"],
		["Дерево", "Огонь", "Землю"],
		["Огонь", "Землю", "Металл"],
		["Земля", "Металл", "Воду"],
		["Металл", "Воду", "Дерево"],
		["Вода", "Дерево", "Огонь"],
	];
	assert.equal(judge(tableEdges(rows)), "PASS");
	const wrong = rows.map((r) => [...r]);
	wrong[3][1] = "Воду";
	wrong[4][1] = "Металл";
	assert.equal(judge(tableEdges(wrong)), "FAIL");
});

test("passive header reverses direction", () => {
	const rows = [
		["Element", "Is generated by", "Is overcome by"],
		["Fire", "Wood", "Water"],
		["Earth", "Fire", "Wood"],
		["Metal", "Earth", "Fire"],
		["Water", "Metal", "Earth"],
		["Wood", "Water", "Metal"],
	];
	assert.equal(judge(tableEdges(rows)), "PASS");
});

test("arrow chains under headings, English and Chinese", () => {
	const text = "Generating cycle (sheng)\nWood → Fire → Earth → Metal → Water → Wood\n\nOvercoming cycle (ke)\n木 → 土 → 水 → 火 → 金 → 木\n";
	assert.equal(judge(textEdges(text)), "PASS");
	const swapped = "Generating cycle\nWood → Fire → Earth → Water → Metal → Wood\nOvercoming cycle\nWood → Earth → Water → Fire → Metal → Wood\n";
	assert.equal(judge(textEdges(swapped)), "FAIL");
});

test("sentences, mixed active and passive", () => {
	const text = "Дерево порождает Огонь. Огонь порождает Землю. Металл порождается Землёй. Металл порождает Воду. Вода порождает Дерево.\n" +
		"Дерево подавляет Землю; Земля подавляет Воду; Вода подавляет Огонь; Огонь подавляет Металл; Металл подавляет Дерево.";
	assert.equal(judge(textEdges(text)), "PASS");
});

test("one cycle only is for the operator", () => {
	const text = "Wood feeds Fire. Fire feeds Earth. Earth feeds Metal. Metal feeds Water. Water feeds Wood.";
	assert.equal(judge(textEdges(text)), "OPERATOR");
	assert.equal(judge([]), "OPERATOR");
});

test("scoring sentence", () => {
	assert.ok(scoringSentence("Если ваша стихия преодолевает стихию соперника, вы получаете очко."));
	assert.ok(scoringSentence("If your element overcomes the opponent's, you win the round."));
	assert.equal(scoringSentence("Wood → Fire → Earth"), null);
});
