# shellcheck shell=bash
# Shared by ./UP, ./DOWN, ./STATUS and tools/check-prerequisites.sh: settings
# from .env (format and defaults in env.example) and what follows from them.
# Sourced, not run.

NERD_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

# KEY=VALUE lines of .env. Read, not sourced: a value is never executed. A
# " #" starts a comment unless the value is quoted; one pair of surrounding
# quotes is removed. Only NERD_* and HF_TOKEN are taken; the environment
# wins over the file, so `NERD_NAME=x ./UP` works. Within the file the last
# line of a name wins, as in other .env readers: `echo NERD_LLAMA=mlx >> .env`
# overrides the NERD_LLAMA=auto copied from env.example. No associative
# arrays: check-prerequisites.sh sources this under macOS's bash 3.2 too.
nerd_load_env() {
  local f=${NERD_ENV_FILE:-$NERD_ROOT/.env} line key val from_file=" "
  [ -f "$f" ] || return 0
  while IFS= read -r line || [ -n "$line" ]; do
    line=${line#"${line%%[![:space:]]*}"}
    case "$line" in ''|'#'*) continue ;; esac
    key=${line%%=*}
    val=${line#*=}
    case "$key" in NERD_*|HF_TOKEN) ;; *) continue ;; esac
    [[ "$key" =~ ^[A-Z_][A-Z0-9_]*$ ]] || continue
    if [[ "$val" =~ ^\"(.*)\"[[:space:]]*(#.*)?$ ]] || [[ "$val" =~ ^\'(.*)\'[[:space:]]*(#.*)?$ ]]; then
      val=${BASH_REMATCH[1]}
    else
      val=${val%%[[:space:]]#*}
      val=${val%"${val##*[![:space:]]}"}
    fi
    # The environment wins; a name this file set already is set again.
    if [[ "$from_file" == *" $key "* ]] || [ -z "${!key+x}" ]; then
      printf -v "$key" '%s' "$val"; export "${key?}"
      [[ "$from_file" == *" $key "* ]] || from_file+="$key "
    fi
  done < "$f"
}

# Compute capability of GPU 0 without the dot ("8.6" -> 86), or empty.
nerd_detect_cuda_arch() {
  command -v nvidia-smi >/dev/null 2>&1 || return 0
  local cc
  cc=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader 2>/dev/null | head -1 | tr -d ' .')
  [[ "$cc" =~ ^[0-9]+$ ]] && echo "$cc"
}

# Highest CUDA version the driver supports, from nvidia-smi's banner ("13.0").
nerd_driver_cuda() {
  command -v nvidia-smi >/dev/null 2>&1 || return 0
  nvidia-smi 2>/dev/null | grep -o 'CUDA Version: *[0-9.]*' | head -1 | grep -o '[0-9.]*$'
}

# True if version $1 >= $2 (dotted numbers).
nerd_ver_ge() {
  [ "$(printf '%s\n%s\n' "$1" "$2" | sort -V | head -1)" = "$2" ]
}

# A CDI spec for NVIDIA GPUs exists (generated by nvidia-ctk, or shipped by the OS).
nerd_have_cdi() {
  local d
  for d in /etc/cdi /var/run/cdi; do
    compgen -G "$d/nvidia*.yaml" >/dev/null 2>&1 && return 0
    compgen -G "$d/nvidia*.json" >/dev/null 2>&1 && return 0
  done
  command -v nvidia-ctk >/dev/null 2>&1 && nvidia-ctk cdi list 2>/dev/null | grep -q 'nvidia.com/gpu=all'
}

# First existing public key, or the configured file.
nerd_keys_file() {
  local f
  if [ -n "${NERD_AUTHORIZED_KEYS_FILE:-}" ]; then
    f=${NERD_AUTHORIZED_KEYS_FILE/#\~/$HOME}
    echo "$f"; return 0
  fi
  for f in "$HOME/.ssh/id_ed25519.pub" "$HOME/.ssh/id_ecdsa.pub" "$HOME/.ssh/id_rsa.pub"; do
    [ -s "$f" ] && { echo "$f"; return 0; }
  done
  return 1
}

# Fill in every derived setting. Call after nerd_load_env.
nerd_settings() {
  NERD_NAME=${NERD_NAME:-nerd}
  NERD_MODEL_VARIANT=${NERD_MODEL_VARIANT:-q1}
  NERD_CTX=${NERD_CTX:-65536}
  NERD_SSH_PORT=${NERD_SSH_PORT:-2222}
  NERD_APP_PORT=${NERD_APP_PORT:-8000}
  NERD_LLAMA_PORT=${NERD_LLAMA_PORT:-8080}
  NERD_BIND=${NERD_BIND:-0.0.0.0}
  NERD_GPU=${NERD_GPU:-auto}
  NERD_MODELS_VOLUME=${NERD_MODELS_VOLUME:-nerd-models}
  NERD_CUDA_ARCH=${NERD_CUDA_ARCH:-$(nerd_detect_cuda_arch)}
  NERD_CUDA_ARCH=${NERD_CUDA_ARCH:-86}
  if [ -z "${NERD_CUDA_VERSION:-}" ]; then
    # Blackwell (10.0 and up) needs CUDA 12.8+; 13.0.1 is the tested one (GB10).
    if [ "${NERD_CUDA_ARCH:0:3}" -ge 100 ] 2>/dev/null; then NERD_CUDA_VERSION=13.0.1; else NERD_CUDA_VERSION=12.4.1; fi
  fi
  # Where the model server runs: container (llama-server in its own container
  # <name>-llm, from the server image, with the GPU), host (llama-server on
  # the machine itself, tools/llama-host.sh) or mlx (mlx-vlm's server on a Mac,
  # the model in Apple's MLX format, tools/mlx-host.sh). auto: host on macOS,
  # where docker cannot reach the GPU, container elsewhere. The agent is
  # always its own container <name>.
  NERD_LLAMA=${NERD_LLAMA:-auto}
  if [ "$NERD_LLAMA" = auto ]; then
    if [ "$(uname -s)" = Darwin ]; then NERD_LLAMA=host; else NERD_LLAMA=container; fi
  fi
  # mlx-vlm's server decodes greedily unless a request names its sampling;
  # these are the model card's values for non-thinking use (Bonsai 2). The
  # agent adds them to requests that do not set them (agent/src/sampling.ts).
  if [ "$NERD_LLAMA" = mlx ]; then
    NERD_SAMPLING=${NERD_SAMPLING:-temperature=0.7,top_p=0.8,top_k=20,presence_penalty=1.5}
  fi
  NERD_IMAGE=${NERD_IMAGE:-nerd:agent}
  NERD_SERVER_IMAGE=${NERD_SERVER_IMAGE:-nerd:server-sm${NERD_CUDA_ARCH//;/-}}
  NERD_LLM_NAME=$NERD_NAME-llm
  # The server as the agent's container reaches it: the host (Docker Desktop
  # names it host.docker.internal; on Linux ./UP maps the name to the host
  # gateway), the server container by name on <name>-net, or loopback when
  # both share NERD_NETWORK's network namespace.
  if [ -z "${NERD_LLAMA_URL:-}" ]; then
    if nerd_on_host; then NERD_LLAMA_URL=http://host.docker.internal:$NERD_LLAMA_PORT/v1
    elif [ -n "${NERD_NETWORK:-}" ]; then NERD_LLAMA_URL=http://127.0.0.1:$NERD_LLAMA_PORT/v1
    else NERD_LLAMA_URL=http://$NERD_LLM_NAME:$NERD_LLAMA_PORT/v1; fi
  fi
}

# The model server runs on this machine, not in a container (NERD_LLAMA=host
# or mlx); ./UP starts it with nerd_host_tool and ./DOWN stops it.
nerd_on_host() { [ "$NERD_LLAMA" = host ] || [ "$NERD_LLAMA" = mlx ]; }
nerd_host_tool() {
  if [ "$NERD_LLAMA" = mlx ]; then echo "$NERD_ROOT/tools/mlx-host.sh"; else echo "$NERD_ROOT/tools/llama-host.sh"; fi
}

# The docker daemon resolves CDI devices (docker info lists spec directories:
# default from Docker 28.2, "features": {"cdi": true} in daemon.json before).
nerd_docker_cdi() {
  docker info --format '{{json .CDISpecDirs}}' 2>/dev/null | grep -q '/'
}

# docker run arguments that pass the GPU (none when llama-server is on the host).
nerd_gpu_args() {
  nerd_on_host && return 0
  case "$NERD_GPU" in
    cdi) echo "--device nvidia.com/gpu=all" ;;
    gpus) echo "--gpus all" ;;
    *) if nerd_have_cdi && nerd_docker_cdi; then echo "--device nvidia.com/gpu=all"; else echo "--gpus all"; fi ;;
  esac
}

# The name under which this machine is probably reached (for the hints only).
nerd_host_name() {
  hostname -f 2>/dev/null || hostname 2>/dev/null || echo "<this-host>"
}

# Everything the calling script prints from here on goes to the terminal and
# to var/log/<name>-<time>.log as well, so a failure is one file to send
# rather than a terminal to copy. Prints the path at once; the caller repeats
# it at the end (nerd_log_path). Works in bash 3.2 (process substitution).
nerd_log() {
  local d=$NERD_ROOT/var/log
  mkdir -p "$d" 2>/dev/null || return 0
  NERD_LOG=$d/$1-$(date +%Y%m%d-%H%M%S).log
  exec > >(tee -a "$NERD_LOG") 2>&1
  echo "[log] $NERD_LOG ($(uname -sm), bash $BASH_VERSION, $(git -C "$NERD_ROOT" log -1 --format='%h %cs' 2>/dev/null))"
}
nerd_log_path() { [ -n "${NERD_LOG:-}" ] && echo "[log] $NERD_LOG — send this file if something went wrong"; return 0; }

# The server on this machine answers /health (NERD_LLAMA=host: llama-server;
# mlx: mlx-vlm's server has one too).
nerd_host_llama_up() {
  curl -sf -m 3 "http://127.0.0.1:$NERD_LLAMA_PORT/health" >/dev/null 2>&1
}

# Port $1 has a listener on this host (TCP, any address).
nerd_port_busy() {
  if command -v ss >/dev/null 2>&1; then
    [ -n "$(ss -Hltn "sport = :$1" 2>/dev/null)" ]
  else
    (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null
  fi
}

# --- docker compose (decision 0012) --------------------------------------------------

# How the server gets the GPU: cdi, gpus, or none (llama-server on the host).
nerd_gpu_mode() {
  nerd_on_host && { echo none; return 0; }
  case "$NERD_GPU" in
    cdi|gpus) echo "$NERD_GPU" ;;
    *) if nerd_have_cdi && nerd_docker_cdi; then echo cdi; else echo gpus; fi ;;
  esac
}

# Everything compose.yaml reads, exported. Call after nerd_settings. The
# public key is read here: compose passes it to the agent as NERD_AUTHORIZED_KEYS.
nerd_compose_env() {
  local keys
  NERD_TMP_SIZE=${NERD_TMP_SIZE:-2g}
  NERD_SHM_SIZE=${NERD_SHM_SIZE:-1g}
  # Loopback in a shared namespace (NERD_NETWORK may be a VPN sidecar: the
  # server must not answer there), all addresses of its own network otherwise.
  if [ -n "${NERD_NETWORK:-}" ]; then NERD_SERVER_HOST=127.0.0.1; else NERD_SERVER_HOST=0.0.0.0; fi
  if [ -n "${NERD_WORKSPACE:-}" ]; then NERD_WORKSPACE_DIR=${NERD_WORKSPACE/#\~/$HOME}; fi
  if [ -z "${NERD_AUTHORIZED_KEYS:-}" ] && keys=$(nerd_keys_file) && [ -s "$keys" ]; then
    NERD_AUTHORIZED_KEYS=$(cat "$keys")
  fi
  export NERD_NAME NERD_IMAGE NERD_SERVER_IMAGE NERD_CUDA_ARCH NERD_CUDA_VERSION \
    NERD_MODEL_VARIANT NERD_CTX NERD_LLAMA_PORT NERD_SERVER_HOST NERD_LLAMA_URL \
    NERD_SSH_PORT NERD_APP_PORT NERD_BIND NERD_TMP_SIZE NERD_SHM_SIZE \
    NERD_MODELS_VOLUME NERD_AUTHORIZED_KEYS
  export NERD_OPERATOR_URL=${NERD_OPERATOR_URL:-} NERD_NETWORK=${NERD_NETWORK:-} \
    NERD_WORKSPACE_DIR=${NERD_WORKSPACE_DIR:-} HF_TOKEN=${HF_TOKEN:-} \
    NERD_MODEL_GGUF=${NERD_MODEL_GGUF:-${NERD_MODEL_FILE:-}} NERD_MODEL_SHA256=${NERD_MODEL_SHA256:-} \
    NERD_MODEL_ALIAS=${NERD_MODEL_ALIAS:-} NERD_SAMPLING=${NERD_SAMPLING:-}
  # llama-server tells the agent its context (/props); mlx-vlm's server has
  # none of its own, so the agent is told NERD_CTX.
  if [ "$NERD_LLAMA" = mlx ]; then export NERD_AGENT_CTX=$NERD_CTX; else export NERD_AGENT_CTX=; fi
  # The server's service is in a profile, so it is left out where llama-server
  # runs on the host.
  if [ "$NERD_LLAMA" = container ]; then export COMPOSE_PROFILES=llm; else export COMPOSE_PROFILES=; fi
}

# The volumes compose.yaml declares external (the model's is NERD_MODELS_VOLUME).
nerd_volumes() {
  echo "$NERD_NAME-ws $NERD_NAME-logs $NERD_NAME-ssh $NERD_NAME-home $NERD_NAME-cache"
}

# The compose files for this machine, as -f arguments, one per line.
nerd_compose_files() {
  local f
  echo -f; echo "$NERD_ROOT/compose.yaml"
  case "$(nerd_gpu_mode)" in
    cdi) echo -f; echo "$NERD_ROOT/compose.cdi.yaml" ;;
    gpus) echo -f; echo "$NERD_ROOT/compose.gpus.yaml" ;;
  esac
  [ -n "${NERD_NETWORK:-}" ] && { echo -f; echo "$NERD_ROOT/compose.netns.yaml"; }
  [ -n "${NERD_WORKSPACE:-}" ] && { echo -f; echo "$NERD_ROOT/compose.workspace-dir.yaml"; }
  nerd_on_host && { echo -f; echo "$NERD_ROOT/compose.host-llama.yaml"; }
  # The operator's own additions (what NERD_DOCKER_ARGS was before compose).
  f=$NERD_ROOT/compose.override.yaml
  [ -f "$f" ] && { echo -f; echo "$f"; }
  return 0
}

# docker compose for this instance. .env is ours, not compose's: compose
# would read it with its own rules, so it gets an empty env file and the
# variables nerd_compose_env exported.
nerd_compose() {
  local files=()
  while IFS= read -r a; do files+=("$a"); done < <(nerd_compose_files)
  docker compose --project-directory "$NERD_ROOT" --env-file /dev/null -p "$NERD_NAME" "${files[@]}" "$@"
}
