# shellcheck shell=bash
# Shared by ./UP, ./DOWN, ./STATUS and tools/check-prerequisites.sh: settings
# from .env (format and defaults in env.example) and what follows from them.
# Sourced, not run.

NERD_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

# KEY=VALUE lines of .env. Read, not sourced: a value is never executed. A
# " #" starts a comment unless the value is quoted; one pair of surrounding
# quotes is removed. Only NERD_* and HF_TOKEN are taken; the environment
# wins over the file, so `NERD_NAME=x ./UP` works.
nerd_load_env() {
  local f=${NERD_ENV_FILE:-$NERD_ROOT/.env} line key val
  [ -f "$f" ] || return 0
  while IFS= read -r line || [ -n "$line" ]; do
    line=${line#"${line%%[![:space:]]*}"}
    case "$line" in ''|'#'*) continue ;; esac
    key=${line%%=*}
    val=${line#*=}
    case "$key" in NERD_*|HF_TOKEN) ;; *) continue ;; esac
    [[ "$key" =~ ^[A-Z_][A-Z0-9_]*$ ]] || continue
    if [[ "$val" =~ ^\"(.*)\"[[:space:]]*(#.*)?$ ]] || [[ "$val" =~ ^\'(.*)\'[[:space:]]*(#.*)?$ ]]; then
      val=${BASH_REMATCH[1]}
    else
      val=${val%%[[:space:]]#*}
      val=${val%"${val##*[![:space:]]}"}
    fi
    # The environment wins: only set what is not set already.
    if [ -z "${!key+x}" ]; then printf -v "$key" '%s' "$val"; export "${key?}"; fi
  done < "$f"
}

# Compute capability of GPU 0 without the dot ("8.6" -> 86), or empty.
nerd_detect_cuda_arch() {
  command -v nvidia-smi >/dev/null 2>&1 || return 0
  local cc
  cc=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader 2>/dev/null | head -1 | tr -d ' .')
  [[ "$cc" =~ ^[0-9]+$ ]] && echo "$cc"
}

# Highest CUDA version the driver supports, from nvidia-smi's banner ("13.0").
nerd_driver_cuda() {
  command -v nvidia-smi >/dev/null 2>&1 || return 0
  nvidia-smi 2>/dev/null | grep -o 'CUDA Version: *[0-9.]*' | head -1 | grep -o '[0-9.]*$'
}

# True if version $1 >= $2 (dotted numbers).
nerd_ver_ge() {
  [ "$(printf '%s\n%s\n' "$1" "$2" | sort -V | head -1)" = "$2" ]
}

# A CDI spec for NVIDIA GPUs exists (generated by nvidia-ctk, or shipped by the OS).
nerd_have_cdi() {
  local d
  for d in /etc/cdi /var/run/cdi; do
    compgen -G "$d/nvidia*.yaml" >/dev/null 2>&1 && return 0
    compgen -G "$d/nvidia*.json" >/dev/null 2>&1 && return 0
  done
  command -v nvidia-ctk >/dev/null 2>&1 && nvidia-ctk cdi list 2>/dev/null | grep -q 'nvidia.com/gpu=all'
}

# First existing public key, or the configured file.
nerd_keys_file() {
  local f
  if [ -n "${NERD_AUTHORIZED_KEYS_FILE:-}" ]; then
    f=${NERD_AUTHORIZED_KEYS_FILE/#\~/$HOME}
    echo "$f"; return 0
  fi
  for f in "$HOME/.ssh/id_ed25519.pub" "$HOME/.ssh/id_ecdsa.pub" "$HOME/.ssh/id_rsa.pub"; do
    [ -s "$f" ] && { echo "$f"; return 0; }
  done
  return 1
}

# Fill in every derived setting. Call after nerd_load_env.
nerd_settings() {
  NERD_NAME=${NERD_NAME:-nerd}
  NERD_MODEL_VARIANT=${NERD_MODEL_VARIANT:-q1}
  NERD_CTX=${NERD_CTX:-65536}
  NERD_SSH_PORT=${NERD_SSH_PORT:-2222}
  NERD_APP_PORT=${NERD_APP_PORT:-8000}
  NERD_LLAMA_PORT=${NERD_LLAMA_PORT:-8080}
  NERD_BIND=${NERD_BIND:-0.0.0.0}
  NERD_GPU=${NERD_GPU:-auto}
  NERD_MODELS_VOLUME=${NERD_MODELS_VOLUME:-nerd-models}
  NERD_CUDA_ARCH=${NERD_CUDA_ARCH:-$(nerd_detect_cuda_arch)}
  NERD_CUDA_ARCH=${NERD_CUDA_ARCH:-86}
  if [ -z "${NERD_CUDA_VERSION:-}" ]; then
    # Blackwell (10.0 and up) needs CUDA 12.8+; 13.0.1 is the tested one (GB10).
    if [ "${NERD_CUDA_ARCH:0:3}" -ge 100 ] 2>/dev/null; then NERD_CUDA_VERSION=13.0.1; else NERD_CUDA_VERSION=12.4.1; fi
  fi
  # Where llama-server runs: container (its own container <name>-llm, from
  # the server image, with the GPU) or host (on the machine itself,
  # tools/llama-host.sh). auto: host on macOS, where docker cannot reach the
  # GPU, container elsewhere. The agent is always its own container <name>.
  NERD_LLAMA=${NERD_LLAMA:-auto}
  if [ "$NERD_LLAMA" = auto ]; then
    if [ "$(uname -s)" = Darwin ]; then NERD_LLAMA=host; else NERD_LLAMA=container; fi
  fi
  NERD_IMAGE=${NERD_IMAGE:-nerd:agent}
  NERD_SERVER_IMAGE=${NERD_SERVER_IMAGE:-nerd:server-sm${NERD_CUDA_ARCH//;/-}}
  NERD_LLM_NAME=$NERD_NAME-llm
  # The server as the agent's container reaches it: the host (Docker Desktop
  # names it host.docker.internal; on Linux ./UP maps the name to the host
  # gateway), the server container by name on <name>-net, or loopback when
  # both share NERD_NETWORK's network namespace.
  if [ -z "${NERD_LLAMA_URL:-}" ]; then
    if [ "$NERD_LLAMA" = host ]; then NERD_LLAMA_URL=http://host.docker.internal:$NERD_LLAMA_PORT/v1
    elif [ -n "${NERD_NETWORK:-}" ]; then NERD_LLAMA_URL=http://127.0.0.1:$NERD_LLAMA_PORT/v1
    else NERD_LLAMA_URL=http://$NERD_LLM_NAME:$NERD_LLAMA_PORT/v1; fi
  fi
}

# The docker daemon resolves CDI devices (docker info lists spec directories:
# default from Docker 28.2, "features": {"cdi": true} in daemon.json before).
nerd_docker_cdi() {
  docker info --format '{{json .CDISpecDirs}}' 2>/dev/null | grep -q '/'
}

# docker run arguments that pass the GPU (none when llama-server is on the host).
nerd_gpu_args() {
  [ "$NERD_LLAMA" = host ] && return 0
  case "$NERD_GPU" in
    cdi) echo "--device nvidia.com/gpu=all" ;;
    gpus) echo "--gpus all" ;;
    *) if nerd_have_cdi && nerd_docker_cdi; then echo "--device nvidia.com/gpu=all"; else echo "--gpus all"; fi ;;
  esac
}

# The name under which this machine is probably reached (for the hints only).
nerd_host_name() {
  hostname -f 2>/dev/null || hostname 2>/dev/null || echo "<this-host>"
}

# The host's llama-server answers /health (NERD_LLAMA=host).
nerd_host_llama_up() {
  curl -sf -m 3 "http://127.0.0.1:$NERD_LLAMA_PORT/health" >/dev/null 2>&1
}

# Port $1 has a listener on this host (TCP, any address).
nerd_port_busy() {
  if command -v ss >/dev/null 2>&1; then
    [ -n "$(ss -Hltn "sport = :$1" 2>/dev/null)" ]
  else
    (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null
  fi
}
