#!/usr/bin/env python3
"""Pin tools/mlx-requirements.in for pip --require-hashes (tools/mlx-host.sh).

    python3 tools/mlx-lock.py > tools/mlx-requirements.txt

Runs on any machine: pip resolves and downloads the wheels a Mac with Apple
silicon would get (macOS 14, 15 and 26 tags, CPython 3.12 and 3.13) into a
temporary directory, and every package gets one line with the sha256 of each
of its wheels. A package whose version differs between the Python versions
gets a line per version with a python_version marker.
"""

import hashlib
import os
import re
import subprocess
import sys
import tempfile
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
PLATFORMS = ["macosx_14_0_arm64", "macosx_15_0_arm64", "macosx_26_0_arm64"]
PYTHONS = ["3.12", "3.13"]


def norm(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def main() -> int:
    src = os.path.join(HERE, "mlx-requirements.in")
    with tempfile.TemporaryDirectory() as wdir:
        for plat in PLATFORMS:
            for py in PYTHONS:
                subprocess.run(
                    [sys.executable, "-m", "pip", "download", "--quiet", "--disable-pip-version-check",
                     "--only-binary=:all:", "--platform", plat, "--python-version", py,
                     "--implementation", "cp", "-d", wdir, "-r", src],
                    check=True, stdout=sys.stderr)
        cp = {"cp" + p.replace(".", ""): p for p in PYTHONS}
        by = defaultdict(lambda: {"hashes": set(), "pys": set()})
        for f in sorted(os.listdir(wdir)):
            if not f.endswith(".whl"):
                sys.exit("not a wheel (an sdist would need building on the Mac): " + f)
            parts = f[:-4].split("-")
            name, version, pytag = parts[0], parts[1], parts[-3]
            if pytag.startswith("cp3") and pytag not in cp and "abi3" not in f:
                continue
            used = set(PYTHONS) if not pytag.startswith("cp3") or "abi3" in f else {cp[pytag]}
            with open(os.path.join(wdir, f), "rb") as fh:
                h = hashlib.sha256(fh.read()).hexdigest()
            by[(norm(name), version)]["hashes"].add(h)
            by[(norm(name), version)]["pys"] |= used
    versions = defaultdict(list)
    for (name, version), v in by.items():
        versions[name].append((version, v))
    print("# Generated by tools/mlx-lock.py from tools/mlx-requirements.in: the wheels pip")
    print("# picks for macOS arm64 (" + ", ".join(PLATFORMS) + "), CPython " + ", ".join(PYTHONS) + ".")
    print("# tools/mlx-host.sh installs it with --require-hashes. Do not edit by hand.")
    for name in sorted(versions):
        for version, v in sorted(versions[name]):
            marker = ""
            if len(versions[name]) > 1:
                marker = " ; " + " or ".join('python_version == "%s"' % p for p in sorted(v["pys"]))
            lines = ["--hash=sha256:" + h for h in sorted(v["hashes"])]
            print("%s==%s%s \\\n    %s" % (name, version, marker, " \\\n    ".join(lines)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
